service_name: '3e4dbc22-c5e8-4e57-8d56-8e862b759480'

http:
  url: http://0.0.0.0:9000
  cors:
    access_control_allow_headers:
      - Content-Type
      - Cache-Control
      - Authorization
      - X-Total-Count
    access_control_allow_origin:
      - https://go2.uiscom.ru

uc_flow_node:
  register_on_start: false
  execute_view_queue_size: 500
  execute_view_workers: 5
  private_url: https://e0e7-212-94-17-230.ngrok.io
  public_url: https://e0e7-212-94-17-230.ngrok.io
  uc_flow:
    domain: https://uc-flow-v2-pp-api.comagic.ru
    jwt_secret: 999